---
- apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    state: present
    validate_certs: no
  when: ( DEPENDENCIA is success )
  register: REPOSITORIO

- apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    state: present
    validate_certs: no
  register: REPOKEY
  when: ( REPOSITORIO is success )

- apt:
    name: 'postgresql-10'
    state: present
    update_cache: true
  when: ( REPOKEY is success )
...
